public class DynamicDataTableConstant {
    
    public static final Set<String> standardAuditFields=new Set<String>{'Owner', 'CreatedBy', 'ModifiedBy'};
    public static final String standardFieldName ='Name';
    public static final String customIconName ='custom:';
    public static final String standardIconName ='standard:';
    public static final String fieldLabelIdSuffix ='ID' ;
    public static final String underscoreRSuffix ='__r' ;
    public static final String underscoreCSuffix ='__c' ;
    public static final String picklistString ='PICKLIST';
    public static final String NoneString ='--None--';
    public static final String dotOperator ='.';
    public static final String secondString =':00';
    public static final String spaceString =' ';
    public static final String forSlashString ='/';
    public static final String svgString ='.svg';
    public static final String recordSaveString ='Record Saved Successfully';
    public static final String failedString ='Failed';
    public static final String failedDMLString ='Failed:The row you are trying to update is missing required fields. Please include these required fields in your SOQL query or ensure they are populated in the backend before updating. Required Fields are:- ';
    public static final String openSquareString ='[';
    public static final String closeSquareString =']';
    public static final String fieldsListRegex ='(?i)SELECT\\s+(.*?)\\s+FROM';
    public static final String objectNameRegex ='(?i)FROM\\s+(\\w+)';
    public static final String queryString ='query' ;  
    public static final String fieldString ='fields' ;
    public static final String idString ='Id' ;
    
    
    
}